import "../../styles/global.css";
import Header from "../../components/common/Header/Header";
import Footer from "../../components/common/Footer";
import { Providers } from "../providers";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Rahil Siddique",
  description: "Generated by Next.js"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Rahil Siddique</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <Providers>
          <Header />
          <div className="layout">
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
