import "../../styles/global.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Rahil Siddique",
  description: "Generated by Next.js"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Rahil Siddique</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <div className="layout">
          {children}
        </div>
      </body>
    </html>
  );
}
