import "../styles/global.css";
import Header from "../components/UI/common/Header/Header";
import Footer from "../components/UI/common/Footer";
import { Providers } from "./providers";

export const metadata = {
  title: "Rahil Siddique",
  description: "Generated by Next.js"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body>
        <Providers>
          <Header />
          <div className="layout">
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
