import Link from "next/link";
import Navbar from "../components/Navbar";
import '../styles/global.css'

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body>
        <Link href="/">
          <Navbar />
        </Link>
        {children}
        <div className="text-xl font-bold">this foot</div>
      </body>
    </html>
  );
}
