import Link from "next/link";
import Navbar from "../components/Navbar";
import '../styles/global.css'
import Header from "../components/UI/common/Header/Header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body>
        <Header />
        {children}
        <div className="text-xl font-bold">this foot</div>
      </body>
    </html>
  );
}
